/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118714-ge934fd96c1-20250309"
#endif /* AVUTIL_FFVERSION_H */
